In [2]:
from VarianceThreshold import VarianceThreshold
import numpy as np

In [15]:
# Create a toy array
X = np.array([[1, 2, 1, 3],
                  [5, 1, 4, 3],
                  [0, 1, 1, 3]])

In [23]:
# Create a VarianceThreshold object
selector = VarianceThreshold(threshold= 0)

# Fit the selector to the data
selector.fit_transform(X)

variance does not meet the threshold in:
[[1 2 1]
 [5 1 4]
 [0 1 1]]
